# Generated by Django 3.0.6 on 2020-05-25 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200524_1311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='req',
            name='task',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='token',
            name='token',
            field=models.CharField(max_length=40),
        ),
    ]
