# Generated by Django 3.0.6 on 2020-05-26 20:11

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20200526_2244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='req',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 26, 20, 11, 34, 907508, tzinfo=utc), verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='token',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 26, 20, 11, 34, 907103, tzinfo=utc), verbose_name='Date'),
        ),
    ]
